# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Город')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
                ('show', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('syn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='city.City', verbose_name='Синоним')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'verbose_name': 'Город',
                'ordering': ['order', 'name'],
            },
        ),
    ]
