# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_city_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='country',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
    ]
